# Generated by Django 6.0.8 on 2026-08-11 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_timeslot_metting_time_slot'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='metting',
            constraint=models.UniqueConstraint(fields=('date', 'timeslot'), name='unique_metting_date_timeslot'),
        ),
    ]
