# Generated by Django 6.0.8 on 2026-08-31 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0006_thread_qanda'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'verbose_name': 'News article', 'verbose_name_plural': 'News'},
        ),
        migrations.AddField(
            model_name='news',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('de', 'Deutsch')], default='en', max_length=2),
        ),
        migrations.AlterField(
            model_name='news',
            name='title',
            field=models.CharField(max_length=200),
        ),
        migrations.AddConstraint(
            model_name='news',
            constraint=models.UniqueConstraint(fields=('language', 'title'), name='unique_news_language_title'),
        ),
    ]
