# Generated by Django 6.0.8 on 2026-09-10 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0009_news_alt_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thread',
            name='agent_type',
            field=models.CharField(choices=[('llama3.2:1b', 'llama3.2:1b'), ('smollm:135m', 'smollm:135m'), ('gemma3:270m', 'gemma3:270m')], max_length=20),
        ),
    ]
